[project]
name = "a-dify-plugin"
version = "0"
requires-python = ">=3.12"
dependencies = [
    "dify-plugin",
]

[dependency-groups]
dev = [
    "pytest"
]

[tool.hatch.build.targets.wheel]
packages = ["tools"]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"


